version: "3"

services:
   web:
      container_name: webserver
      image: nginx:alpine
      volumes:
          - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
          - "./www:/var/www/html"
          - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      ports:
          - "8000:80"
      environment:
          - NGINX_HOST=localhost
      command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      restart: always
      depends_on:
          - php
          - db
    php:
      container_name: phpsourse
      image: php:fpm
      restart: always
      volumes:
          - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
          - "./www:/var/www/html"

    db:
      container_name: mysql
      image: mysql:last
      restart: always
      environment:
        - MYSQL_DATABASE= <databasename>
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_USER=
        - MYSQL_PASSWORD=
      volumes:
        - "./data/db/mysql:/var/lib/mysql"