version: "3"

services:
   web:
      image: nginx:alpine
      volumes:
          - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      volumes_from:
        - php
      ports:
          - "80:80"
      environment:
          - NGINX_HOST=localhost
      restart: always
      depends_on:
          - php
          - db
    php:
      image: php:fpm
      restart: always
      volumes:
          - "./www:/var/www/html"
      links:
        - db

    db:
      image: mysql:5.7
      restart: always
      environment:
        - MYSQL_DATABASE= <databasename>
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_USER=
        - MYSQL_PASSWORD=
      volumes:
        - "./data/db/mysql:/var/lib/mysql"
        - ./etc/mysql/my.cnf:/etc/mysql/my.cnf