version: "3"

services:

  wordpress:
    links:
      - db
    build: docker/wordpress
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mysql
      WORDPRESS_DB_PASSWORD: root
      LOCAL_USER_ID: $UID
      LOCAL_USER_NAME: $USER

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=root
    links:
      - db

  db:
    build: docker/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
      - "./etc/mysql/my.cnf:/etc/mysql/my.cnf"

