version: "3"

services:
  web:
    image: nginx:alpine
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    restart: always
    depends_on:
      - php
      - db

  php:
    image: php:5.6.36-fpm
    restart: always
    volumes:
      - ./www:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./data/db/mysql:/var/lib/mysql
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
